import type {
  Espacio,
  Notificacion,
  Pago,
  Reservacion,
  Usuario,
} from "./types"

export const usuariosSeed: Usuario[] = [
  {
    id: "u-admin",
    nombre: "Administrador General",
    correo: "admin@espacios.mx",
    telefono: "33 1111 0000",
    password: "admin123",
    rol: "admin",
    estado: "activo",
    verificacion: "aprobada",
  },
  {
    id: "u-cliente",
    nombre: "Ana López",
    correo: "cliente@espacios.mx",
    telefono: "33 2222 1111",
    password: "cliente123",
    rol: "cliente",
    estado: "activo",
    verificacion: "aprobada",
  },
  {
    id: "u-cliente-2",
    nombre: "Carlos Méndez",
    correo: "carlos@espacios.mx",
    telefono: "55 4444 2222",
    password: "cliente123",
    rol: "cliente",
    estado: "activo",
    verificacion: "pendiente",
  },
  {
    id: "u-prop",
    nombre: "Roberto Díaz",
    correo: "propietario@espacios.mx",
    telefono: "33 3333 2222",
    password: "prop123",
    rol: "propietario",
    estado: "activo",
    verificacion: "aprobada",
  },
  {
    id: "u-prop-2",
    nombre: "Marina Torres",
    correo: "marina@espacios.mx",
    telefono: "81 5555 3333",
    password: "prop123",
    rol: "propietario",
    estado: "activo",
    verificacion: "pendiente",
  },
]

export const espaciosSeed: Espacio[] = [
  {
    id: "e-1",
    propietarioId: "u-prop",
    nombre: "Sala de Juntas Centro",
    descripcion:
      "Sala de juntas moderna ideal para reuniones ejecutivas y presentaciones. Cuenta con pantalla, conexión de alta velocidad y excelente iluminación natural.",
    tipo: "Sala de juntas",
    ciudad: "Guadalajara",
    direccion: "Av. Chapultepec 123, Col. Americana",
    precio: 1200,
    capacidad: 20,
    caracteristicas: ["WiFi", "Aire acondicionado", "Proyector", "Mobiliario"],
    fotos: ["/spaces/sala-juntas.png"],
    estado: "activo",
    bloqueos: [{ id: "b-1", inicio: "2026-08-20", fin: "2026-08-22" }],
    creado: "2026-07-01",
  },
  {
    id: "e-2",
    propietarioId: "u-prop",
    nombre: "Oficina Privada Norte",
    descripcion:
      "Oficina privada equipada para equipos pequeños. Ambiente tranquilo y profesional con vista a la ciudad.",
    tipo: "Oficina privada",
    ciudad: "Monterrey",
    direccion: "Av. Constitución 456, Centro",
    precio: 800,
    capacidad: 6,
    caracteristicas: ["WiFi", "Estacionamiento", "Baños", "Mobiliario"],
    fotos: ["/spaces/oficina-privada.png"],
    estado: "activo",
    bloqueos: [],
    creado: "2026-07-03",
  },
  {
    id: "e-3",
    propietarioId: "u-prop-2",
    nombre: "Salón de Eventos Reforma",
    descripcion:
      "Amplio salón para eventos sociales y corporativos. Capacidad para grandes grupos con montaje flexible.",
    tipo: "Salón de eventos",
    ciudad: "Ciudad de México",
    direccion: "Paseo de la Reforma 789",
    precio: 3500,
    capacidad: 120,
    caracteristicas: [
      "WiFi",
      "Estacionamiento",
      "Baños",
      "Aire acondicionado",
      "Cocina",
    ],
    fotos: ["/spaces/salon-eventos.png"],
    estado: "activo",
    bloqueos: [],
    creado: "2026-07-05",
  },
  {
    id: "e-4",
    propietarioId: "u-prop-2",
    nombre: "Estudio Creativo Roma",
    descripcion:
      "Estudio luminoso con ladrillo expuesto, perfecto para sesiones de fotografía, talleres y grabaciones.",
    tipo: "Estudio creativo",
    ciudad: "Ciudad de México",
    direccion: "Calle Orizaba 45, Col. Roma",
    precio: 1500,
    capacidad: 15,
    caracteristicas: ["WiFi", "Aire acondicionado", "Mobiliario"],
    fotos: ["/spaces/estudio-creativo.png"],
    estado: "activo",
    bloqueos: [],
    creado: "2026-07-08",
  },
  {
    id: "e-5",
    propietarioId: "u-prop",
    nombre: "Coworking Chapultepec",
    descripcion:
      "Espacio de coworking abierto con estaciones de trabajo, salas de reunión y áreas comunes.",
    tipo: "Coworking",
    ciudad: "Ciudad de México",
    direccion: "Av. Chapultepec 200, Col. Juárez",
    precio: 450,
    capacidad: 40,
    caracteristicas: ["WiFi", "Baños", "Aire acondicionado", "Cocina"],
    fotos: ["/spaces/coworking.png"],
    estado: "activo",
    bloqueos: [],
    creado: "2026-07-10",
  },
  {
    id: "e-6",
    propietarioId: "u-prop-2",
    nombre: "Terraza Panorámica",
    descripcion:
      "Terraza en azotea con vista panorámica de la ciudad, ideal para eventos al atardecer y reuniones especiales.",
    tipo: "Terraza",
    ciudad: "Guadalajara",
    direccion: "Av. Vallarta 1500, piso 12",
    precio: 2800,
    capacidad: 80,
    caracteristicas: ["WiFi", "Baños", "Cocina", "Accesibilidad"],
    fotos: ["/spaces/terraza.png"],
    estado: "inactivo",
    bloqueos: [],
    creado: "2026-07-12",
  },
]

export const reservacionesSeed: Reservacion[] = [
  {
    id: "r-1",
    espacioId: "e-1",
    clienteId: "u-cliente",
    inicio: "2026-08-10",
    fin: "2026-08-10",
    dias: 1,
    total: 1200,
    mensaje: "Reunión trimestral del equipo comercial con presentación de resultados.",
    estado: "pendiente",
    creado: "2026-08-01",
  },
  {
    id: "r-2",
    espacioId: "e-2",
    clienteId: "u-cliente",
    inicio: "2026-08-12",
    fin: "2026-08-13",
    dias: 2,
    total: 1600,
    mensaje: "Taller interno de planeación estratégica para ocho colaboradores.",
    estado: "aprobada",
    creado: "2026-08-02",
  },
  {
    id: "r-3",
    espacioId: "e-3",
    clienteId: "u-cliente-2",
    inicio: "2026-09-01",
    fin: "2026-09-01",
    dias: 1,
    total: 3500,
    mensaje: "Celebración de aniversario empresarial con clientes y proveedores.",
    estado: "pendiente",
    creado: "2026-08-03",
  },
]

export const pagosSeed: Pago[] = []

export const notificacionesSeed: Notificacion[] = [
  {
    id: "n-1",
    usuarioId: "u-cliente",
    mensaje: "Tu reservación de Oficina Privada Norte fue aprobada.",
    tipo: "reservacion_aprobada",
    leida: false,
    fecha: "2026-08-02",
  },
  {
    id: "n-2",
    usuarioId: "u-prop",
    mensaje: "Recibiste una nueva solicitud para Sala de Juntas Centro.",
    tipo: "nueva_solicitud",
    leida: false,
    fecha: "2026-08-01",
  },
  {
    id: "n-3",
    usuarioId: "u-prop-2",
    mensaje: "Recibiste una nueva solicitud para Salón de Eventos Reforma.",
    tipo: "nueva_solicitud",
    leida: true,
    fecha: "2026-08-03",
  },
]
